-- Resets and seeds the published course set.
-- Run this in Supabase SQL editor.

begin;

-- Delete dependent rows first to avoid FK violations.
-- (Order matters: resources -> course_modules -> enrollments -> courses)

delete from resources;
delete from course_modules;
delete from enrollments;
delete from student_progress;
delete from forum_posts;
delete from evaluations;
delete from certificates;
delete from complaints;
delete from complaint_replies;
delete from surveys;

delete from courses;

-- Insert the 12 courses (website dataset).
-- UUIDs are generated by default by `courses.id`.

insert into courses (title, description, category, cover_emoji, teacher_id, duration_weeks, is_published, enrollment_code)
values
  ('Electrical Installation', 'Practical electrical installation training.', 'Trades', '⚡', null, 10, true, 'EL12345'),
  ('Solar PV Installation', 'Practical solar PV installation training.', 'Trades', '☀️', null, 10, true, 'SP12345'),
  ('Plumbing', 'Practical plumbing training.', 'Trades', '🚰', null, 10, true, 'PL12345'),
  ('Cosmetology', 'Practical cosmetology training.', 'Health', '💇🏽‍♀️', null, 10, true, 'CT12345'),
  ('Fashion Design', 'Practical fashion design training.', 'Vocational', '🧵', null, 10, true, 'FD12345'),
  ('Regenerative Agriculture', 'Practical regenerative agriculture training.', 'Agriculture', '🌱', null, 10, true, 'RA12345'),
  ('Core Agriculture', 'Core agriculture training.', 'Agriculture', '🌾', null, 10, true, 'CA12345'),
  ('Reproductive Health', 'Reproductive health training.', 'Health', '🩺', null, 10, true, 'RH12345'),
  ('ICT', 'Information and Communication Technology training.', 'Technology', '💻', null, 10, true, 'IT12345'),
  ('Basic Digital Literacy', 'Basic digital literacy training.', 'Technology', '📱', null, 10, true, 'DL12345'),
  ('Entrepreneurship', 'Entrepreneurship training.', 'Business', '🚀', null, 10, true, 'EP12345'),
  ('Beadwork', 'Practical beadwork training.', 'Vocational', '🧶', null, 10, true, 'BW12345')
on conflict (enrollment_code) do nothing;

commit;

