-- Resets and seeds the 13 correct courses.
-- Run this in Supabase SQL editor (or via the CLI).

begin;

-- Delete dependent rows first to avoid FK violations.
-- (Order matters: resources -> course_modules -> enrollments -> courses)

delete from resources;
delete from course_modules;
delete from enrollments;
delete from student_progress;
delete from forum_posts;
delete from evaluations;
delete from certificates;
delete from complaints;
delete from complaint_replies;
delete from surveys;

-- Hard reset the published set deterministically
delete from courses;

-- Insert the 13 courses.

-- NOTE: UUIDs are generated by default. If your deployment uses a different schema
-- (e.g., different column names), adjust accordingly.

insert into courses (title, description, category, cover_emoji, duration_weeks, is_published, enrollment_code)
values
  ('Electrical Installation','Practical electrical installation training','Trades','⚡',6,true,'EL12345'),
  ('Solar PV Installation','Practical solar PV installation training','Trades','☀️',6,true,'SP12345'),
  ('Plumbing','Practical plumbing training','Trades','🚰',6,true,'PL12345'),
  ('Cosmetology','Practical cosmetology training','Health','💇🏽‍♀️',6,true,'CT12345'),
  ('Fashion Design','Practical fashion design training','Vocational','🧵',6,true,'FD12345'),
  ('Regenerative Agriculture','Practical regenerative agriculture training','Agriculture','🌱',6,true,'RA12345'),
  ('Core Agriculture','Core agriculture training','Agriculture','🌾',6,true,'CA12345'),
  ('Reproductive Health','Reproductive health training','Health','🩺',6,true,'RH12345'),
  ('ICT','Information and Communication Technology training','Technology','💻',6,true,'IT12345'),
  ('Basic Digital Literacy','Basic digital literacy training','Technology','📱',4,true,'DL12345'),
  ('Entrepreneurship','Entrepreneurship training','Business','🚀',5,true,'EP12345'),
  ('Beadwork','Practical beadwork training','Vocational','🧶',5,true,'BW12345');







commit;

