-- Resets and seeds the 13 correct courses.
-- Run this in Supabase SQL editor (or via the CLI).

begin;

-- Delete dependent rows first to avoid FK violations.
-- (Order matters: resources -> course_modules -> enrollments -> courses)

delete from resources;
delete from course_modules;
delete from enrollments;
delete from student_progress;
delete from forum_posts;
delete from evaluations;
delete from certificates;
delete from complaints;
delete from complaint_replies;
delete from surveys;

delete from courses;

-- Insert the 13 courses.
-- NOTE: UUIDs are generated by default. If your deployment uses a different schema
-- (e.g., different column names), adjust accordingly.

insert into courses (title, description, category, cover_emoji, duration_weeks, is_published, enrollment_code)
values
  ('Electrical Installation','Practical electrical installation training','Trades','⚡',6,true,'ELC00001'),
  ('Solar PV Installation','Practical solar PV installation training','Trades','☀️',6,true,'SOL00001'),
  ('Plumbing','Practical plumbing training','Trades','🚰',6,true,'PLM00001'),
  ('Cosmetology','Practical cosmetology training','Health','💇🏽‍♀️',6,true,'CSM00001'),
  ('Fashion Design','Practical fashion design training','Vocational','🧵',6,true,'FAS00001'),
  ('Regenerative Agriculture','Practical regenerative agriculture training','Agriculture','🌱',6,true,'RGA00001'),
  ('Core Agriculture','Core agriculture training','Agriculture','🌾',6,true,'AGR00001'),
  ('Reproductive Health','Reproductive health training','Health','🩺',6,true,'RPH00001'),
  ('ICT','Information and Communication Technology training','Technology','💻',6,true,'ICT00001'),
  ('Basic Digital Literacy','Basic digital literacy training','Technology','📱',4,true,'BDL00001'),
  ('Entrepreneurship','Entrepreneurship training','Business','🚀',5,true,'ENT00001'),
  ('Beadwork','Practical beadwork training','Vocational','🧶',5,true,'BEA00001'),
  ('Fashion Design (Advanced)','Advanced fashion design training','Vocational','✂️',6,true,'FAS00002');

commit;

